/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/project-evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evaluations */
        get: operations["list_evaluations_api_project_evaluations_get"];
        put?: never;
        /** Create Evaluation */
        post: operations["create_evaluation_api_project_evaluations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-evaluations/{evaluation_id}/question-policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Question Policy */
        patch: operations["update_question_policy_api_project_evaluations__evaluation_id__question_policy_patch"];
        trace?: never;
    };
    "/api/project-evaluations/{evaluation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation */
        get: operations["get_evaluation_api_project_evaluations__evaluation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-evaluations/{evaluation_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation Status */
        get: operations["get_evaluation_status_api_project_evaluations__evaluation_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-evaluations/{evaluation_id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join Evaluation */
        post: operations["join_evaluation_api_project_evaluations__evaluation_id__join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-evaluations/{evaluation_id}/artifacts/zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Zip Artifact */
        post: operations["upload_zip_artifact_api_project_evaluations__evaluation_id__artifacts_zip_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-evaluations/{evaluation_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Artifacts */
        get: operations["list_artifacts_api_project_evaluations__evaluation_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-evaluations/{evaluation_id}/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract Context */
        post: operations["extract_context_api_project_evaluations__evaluation_id__extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-evaluations/{evaluation_id}/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Context */
        get: operations["get_context_api_project_evaluations__evaluation_id__context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-evaluations/{evaluation_id}/questions/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Questions */
        post: operations["generate_questions_api_project_evaluations__evaluation_id__questions_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-evaluations/{evaluation_id}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Questions */
        get: operations["list_questions_api_project_evaluations__evaluation_id__questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-evaluations/{evaluation_id}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_api_project_evaluations__evaluation_id__sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-evaluations/{evaluation_id}/sessions/{session_id}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Turns */
        get: operations["list_turns_api_project_evaluations__evaluation_id__sessions__session_id__turns_get"];
        put?: never;
        /** Submit Turn */
        post: operations["submit_turn_api_project_evaluations__evaluation_id__sessions__session_id__turns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-evaluations/{evaluation_id}/sessions/{session_id}/interview/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Interview State */
        get: operations["get_interview_state_api_project_evaluations__evaluation_id__sessions__session_id__interview_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-evaluations/{evaluation_id}/sessions/{session_id}/interview/transcribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transcribe Interview Audio */
        post: operations["transcribe_interview_audio_api_project_evaluations__evaluation_id__sessions__session_id__interview_transcribe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-evaluations/{evaluation_id}/sessions/{session_id}/interview/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Interview Answer */
        post: operations["submit_interview_answer_api_project_evaluations__evaluation_id__sessions__session_id__interview_answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-evaluations/{evaluation_id}/sessions/{session_id}/interview/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Interview */
        post: operations["complete_interview_api_project_evaluations__evaluation_id__sessions__session_id__interview_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-evaluations/{evaluation_id}/sessions/{session_id}/interview/abort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abort Interview */
        post: operations["abort_interview_api_project_evaluations__evaluation_id__sessions__session_id__interview_abort_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-evaluations/{evaluation_id}/sessions/{session_id}/interview/tts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Synthesize Interview Speech */
        post: operations["synthesize_interview_speech_api_project_evaluations__evaluation_id__sessions__session_id__interview_tts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-evaluations/{evaluation_id}/sessions/{session_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Session */
        post: operations["complete_session_api_project_evaluations__evaluation_id__sessions__session_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-evaluations/{evaluation_id}/reports/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Latest Report */
        get: operations["get_latest_report_api_project_evaluations__evaluation_id__reports_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-evaluations/{evaluation_id}/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_api_project_evaluations__evaluation_id__reports__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interview/{evaluation_id}/{session_id}/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Open Interview Page */
        get: operations["open_interview_page_interview__evaluation_id___session_id__open_get"];
        put?: never;
        /** Set Interview Cookie */
        post: operations["set_interview_cookie_interview__evaluation_id___session_id__open_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interview/{evaluation_id}/{session_id}/enter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Enter Interview */
        get: operations["enter_interview_interview__evaluation_id___session_id__enter_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interview/{evaluation_id}/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Staged Interview Page */
        get: operations["get_staged_interview_page_interview__evaluation_id___session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interview/{evaluation_id}/{session_id}/voice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Voice Interview Page */
        get: operations["get_voice_interview_page_interview__evaluation_id___session_id__voice_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interview/{evaluation_id}/{session_id}/report-redirect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Redirect To Streamlit Report
         * @description 검증 완료 후 학생을 Next.js 리포트 페이지로 보내는 경로.
         *
         *     `interview_session_{session_id}` 쿠키에서 세션 토큰을 읽어
         *     Next.js URL 쿼리에 동봉한다. Next.js Route Handler 가 토큰을
         *     다시 httpOnly 쿠키로 변환해 클라이언트에 심는다.
         */
        get: operations["redirect_to_streamlit_report_interview__evaluation_id___session_id__report_redirect_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArchitectureEdgeRead */
        ArchitectureEdgeRead: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /**
             * Label
             * @default
             */
            label: string;
        };
        /** ArchitectureNodeRead */
        ArchitectureNodeRead: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Layer */
            layer: string;
        };
        /** ArchitectureRead */
        ArchitectureRead: {
            /**
             * Style
             * @default
             */
            style: string;
            /**
             * Summary
             * @default
             */
            summary: string;
            /** Layers */
            layers?: string[];
            /** Modules */
            modules?: string[];
            /** Nodes */
            nodes?: components["schemas"]["ArchitectureNodeRead"][];
            /** Edges */
            edges?: components["schemas"]["ArchitectureEdgeRead"][];
        };
        /**
         * ArtifactSourceType
         * @enum {string}
         */
        ArtifactSourceType: "zip" | "document" | "code" | "text" | "ignored";
        /**
         * ArtifactStatus
         * @enum {string}
         */
        ArtifactStatus: "extracted" | "skipped" | "failed";
        /** ArtifactUploadResult */
        ArtifactUploadResult: {
            /** Evaluation Id */
            evaluation_id: string;
            /** Accepted Count */
            accepted_count: number;
            /** Skipped Count */
            skipped_count: number;
            /**
             * Ignored Count
             * @default 0
             */
            ignored_count: number;
            /**
             * Empty Text Count
             * @default 0
             */
            empty_text_count: number;
            /**
             * File Too Large Count
             * @default 0
             */
            file_too_large_count: number;
            /**
             * Processed File Limit Count
             * @default 0
             */
            processed_file_limit_count: number;
            /**
             * Failed Count
             * @default 0
             */
            failed_count: number;
            /** Reason Counts */
            reason_counts?: {
                [key: string]: number;
            };
            /** Processing Limits */
            processing_limits?: {
                [key: string]: number;
            };
            /** Supported Extensions */
            supported_extensions?: string[];
            /** Artifacts */
            artifacts: components["schemas"]["ProjectArtifactRead"][];
        };
        /**
         * BloomLevel
         * @enum {string}
         */
        BloomLevel: "기억" | "이해" | "적용" | "분석" | "평가" | "창안";
        /** Body_set_interview_cookie_interview__evaluation_id___session_id__open_post */
        Body_set_interview_cookie_interview__evaluation_id___session_id__open_post: {
            /** Session Token */
            session_token: string;
        };
        /** Body_transcribe_interview_audio_api_project_evaluations__evaluation_id__sessions__session_id__interview_transcribe_post */
        Body_transcribe_interview_audio_api_project_evaluations__evaluation_id__sessions__session_id__interview_transcribe_post: {
            /** @default answer */
            mode: components["schemas"]["InterviewTurnMode"];
            /** Audio */
            audio: string;
        };
        /** Body_upload_zip_artifact_api_project_evaluations__evaluation_id__artifacts_zip_post */
        Body_upload_zip_artifact_api_project_evaluations__evaluation_id__artifacts_zip_post: {
            /** File */
            file: string;
        };
        /** EvaluationReportRead */
        EvaluationReportRead: {
            /** Id */
            id: string;
            /** Evaluation Id */
            evaluation_id: string;
            /** Session Id */
            session_id: string;
            final_decision: components["schemas"]["FinalDecision"];
            /** Authenticity Score */
            authenticity_score: number;
            /**
             * Total Score
             * @default 0
             */
            total_score: number;
            /**
             * Total Max Score
             * @default 100
             */
            total_max_score: number;
            /** Summary */
            summary: string;
            /** Area Analyses */
            area_analyses?: {
                [key: string]: unknown;
            }[];
            /** Question Evaluations */
            question_evaluations?: {
                [key: string]: unknown;
            }[];
            /** Bloom Summary */
            bloom_summary?: {
                [key: string]: unknown;
            }[];
            /** Evidence Alignment */
            evidence_alignment?: string[];
            /** Strengths */
            strengths?: string[];
            /** Suspicious Points */
            suspicious_points?: string[];
            /** Recommended Followups */
            recommended_followups?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * EvaluationStatus
         * @enum {string}
         */
        EvaluationStatus: "created" | "uploaded" | "analyzed" | "questions_generated" | "interviewing" | "reported";
        /** ExtractedProjectContextRead */
        ExtractedProjectContextRead: {
            /** Id */
            id: string;
            /** Evaluation Id */
            evaluation_id: string;
            /** Summary */
            summary: string;
            /** Tech Stack */
            tech_stack?: components["schemas"]["TechStackItemRead"][];
            /** Features */
            features?: string[];
            architecture?: components["schemas"]["ArchitectureRead"];
            /** Student Implementation Risks */
            student_implementation_risks?: components["schemas"]["StudentImplementationRiskRead"][];
            structural_facts?: components["schemas"]["StructuralFactsRead"];
            /** Question Targets */
            question_targets?: string[];
            /** Rag Status */
            rag_status?: {
                [key: string]: unknown;
            };
            /** Areas */
            areas?: components["schemas"]["ProjectAreaRead"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * FinalDecision
         * @enum {string}
         */
        FinalDecision: "검증 통과" | "추가 확인 필요" | "신뢰 낮음";
        /** FollowUpExchange */
        FollowUpExchange: {
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InterviewQuestionRead */
        InterviewQuestionRead: {
            /** Id */
            id: string;
            /** Evaluation Id */
            evaluation_id: string;
            /** Project Area Id */
            project_area_id: string | null;
            /** Question */
            question: string;
            /** Intent */
            intent: string;
            bloom_level: components["schemas"]["BloomLevel"];
            /** Expected Answer */
            expected_answer: string;
            /** Scoring Rubric */
            scoring_rubric?: components["schemas"]["ScoringRubricItem"][];
            /** Max Points */
            max_points: number;
            /** Source Refs */
            source_refs?: components["schemas"]["SourceReference"][];
            /** Order Index */
            order_index: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** InterviewSessionRead */
        InterviewSessionRead: {
            /** Id */
            id: string;
            /** Evaluation Id */
            evaluation_id: string;
            /**
             * Participant Name
             * @default
             */
            participant_name: string;
            /**
             * Session Token
             * @default
             */
            session_token: string;
            status: components["schemas"]["InterviewSessionStatus"];
            /** Current Question Index */
            current_question_index: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at?: string | null;
        };
        /**
         * InterviewSessionStatus
         * @enum {string}
         */
        InterviewSessionStatus: "created" | "in_progress" | "completed";
        /** InterviewSpeechSynthesisRequest */
        InterviewSpeechSynthesisRequest: {
            /** Text */
            text: string;
            /** Voice */
            voice?: string | null;
            /** Instructions */
            instructions?: string | null;
        };
        /** InterviewTranscriptionRead */
        InterviewTranscriptionRead: {
            /** Transcript */
            transcript: string;
            mode: components["schemas"]["InterviewTurnMode"];
        };
        /** InterviewTurnCreate */
        InterviewTurnCreate: {
            /** Question Id */
            question_id: string;
            /** Answer Text */
            answer_text: string;
        };
        /** InterviewTurnFlowRequest */
        InterviewTurnFlowRequest: {
            /** @default answer */
            mode: components["schemas"]["InterviewTurnMode"];
            /**
             * Answer Text
             * @default
             */
            answer_text: string;
            /**
             * Draft Answer
             * @default
             */
            draft_answer: string;
            /**
             * Follow Up Question
             * @default
             */
            follow_up_question: string;
            /**
             * Follow Up Reason
             * @default
             */
            follow_up_reason: string;
            /** Current Question Id */
            current_question_id?: string | null;
            /** 누적 대화 (follow_up 모드에서 프론트가 매 요청에 그대로 전달) */
            conversation_history?: components["schemas"]["QuestionExchange"] | null;
        };
        /** InterviewTurnFlowResponse */
        InterviewTurnFlowResponse: {
            status: components["schemas"]["InterviewTurnFlowStatus"];
            /** Message */
            message: string;
            /**
             * Draft Answer
             * @default
             */
            draft_answer: string;
            /** Follow Up Question */
            follow_up_question?: string | null;
            /**
             * Follow Up Reason
             * @default
             */
            follow_up_reason: string;
            next_mode?: components["schemas"]["InterviewTurnMode"] | null;
            turn?: components["schemas"]["InterviewTurnRead"] | null;
            next_question?: components["schemas"]["InterviewQuestionRead"] | null;
            report?: components["schemas"]["EvaluationReportRead"] | null;
            /** NEED_FOLLOW_UP 시 서버가 갱신해 돌려주는 누적 대화. 프론트는 그대로 다음 요청에 동봉. */
            conversation_history?: components["schemas"]["QuestionExchange"] | null;
        };
        /**
         * InterviewTurnFlowStatus
         * @enum {string}
         */
        InterviewTurnFlowStatus: "need_follow_up" | "turn_submitted" | "ready_to_complete" | "completed";
        /**
         * InterviewTurnMode
         * @enum {string}
         */
        InterviewTurnMode: "answer" | "follow_up" | "end";
        /** InterviewTurnRead */
        InterviewTurnRead: {
            /** Id */
            id: string;
            /** Session Id */
            session_id: string;
            /** Question Id */
            question_id: string;
            /** Question Text */
            question_text: string;
            /** Answer Text */
            answer_text: string;
            /** Score */
            score: number;
            /** Evaluation Summary */
            evaluation_summary: string;
            /** Rubric Scores */
            rubric_scores?: components["schemas"]["RubricScoreItem"][];
            /** Evidence Matches */
            evidence_matches?: string[];
            /** Evidence Mismatches */
            evidence_mismatches?: string[];
            /** Suspicious Points */
            suspicious_points?: string[];
            /** Strengths */
            strengths?: string[];
            /** Follow Up Question */
            follow_up_question?: string | null;
            /**
             * Follow Up Reason
             * @default
             */
            follow_up_reason: string;
            /** Finalized Score */
            finalized_score?: number | null;
            conversation_history?: components["schemas"]["QuestionExchange"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** JoinEvaluationRead */
        JoinEvaluationRead: {
            evaluation: components["schemas"]["ProjectEvaluationRead"];
            session: components["schemas"]["InterviewSessionRead"];
            /** Interview Url Path */
            interview_url_path: string;
        };
        /** JoinEvaluationRequest */
        JoinEvaluationRequest: {
            /** Participant Name */
            participant_name: string;
            /** Room Password */
            room_password: string;
        };
        /** ProjectAreaRead */
        ProjectAreaRead: {
            /** Id */
            id: string;
            /** Evaluation Id */
            evaluation_id: string;
            /** Name */
            name: string;
            /** Summary */
            summary: string;
            /**
             * Role In Project
             * @default
             */
            role_in_project: string;
            /** Key Concerns */
            key_concerns?: string[];
            /** Confidence */
            confidence: number;
            /** Source Refs */
            source_refs?: components["schemas"]["SourceReference"][];
        };
        /** ProjectArtifactRead */
        ProjectArtifactRead: {
            /** Id */
            id: string;
            /** Evaluation Id */
            evaluation_id: string;
            /** Source Path */
            source_path: string;
            source_type: components["schemas"]["ArtifactSourceType"];
            status: components["schemas"]["ArtifactStatus"];
            /** Char Count */
            char_count: number;
            /** Text Preview */
            text_preview: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ProjectEvaluationCreate */
        ProjectEvaluationCreate: {
            /** Project Name */
            project_name: string;
            /**
             * Candidate Name
             * @default
             */
            candidate_name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Room Name
             * @default
             */
            room_name: string;
            /**
             * Room Password
             * @default
             */
            room_password: string;
            question_policy?: components["schemas"]["QuestionGenerationPolicy"];
        };
        /** ProjectEvaluationRead */
        ProjectEvaluationRead: {
            /** Id */
            id: string;
            /** Project Name */
            project_name: string;
            /** Candidate Name */
            candidate_name: string;
            /** Description */
            description: string;
            /**
             * Room Name
             * @default
             */
            room_name: string;
            status: components["schemas"]["EvaluationStatus"];
            question_policy: components["schemas"]["QuestionGenerationPolicy"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProjectEvaluationStatusRead */
        ProjectEvaluationStatusRead: {
            /** Evaluation Id */
            evaluation_id: string;
            /** Status */
            status: string;
            /** Phase */
            phase: string;
            /** Has Artifacts */
            has_artifacts: boolean;
            /** Has Context */
            has_context: boolean;
            /** Rag Status */
            rag_status?: {
                [key: string]: unknown;
            };
            /** Question Count */
            question_count: number;
            /** Expected Question Count */
            expected_question_count: number;
            /** Questions Ready */
            questions_ready: boolean;
            /** Can Generate Questions */
            can_generate_questions: boolean;
            /** Can Join */
            can_join: boolean;
            /**
             * Blocked Reason
             * @default
             */
            blocked_reason: string;
            /** User Message */
            user_message: string;
            /** Check Targets */
            check_targets?: string[];
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
        };
        /** ProjectEvaluationSummaryRead */
        ProjectEvaluationSummaryRead: {
            /** Id */
            id: string;
            /**
             * Room Name
             * @default
             */
            room_name: string;
            /** Project Name */
            project_name: string;
            /**
             * Candidate Name
             * @default
             */
            candidate_name: string;
            status: components["schemas"]["EvaluationStatus"];
            /** Question Count */
            question_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** QuestionExchange */
        QuestionExchange: {
            /** Student Answer */
            student_answer: string;
            /** Follow Ups */
            follow_ups?: components["schemas"]["FollowUpExchange"][];
        };
        /** QuestionGenerationPolicy */
        QuestionGenerationPolicy: {
            /**
             * Total Question Count
             * @default 6
             */
            total_question_count: number;
            /** Bloom Ratios */
            bloom_ratios?: {
                [key: string]: number;
            };
            /** Bloom Distribution */
            bloom_distribution?: {
                [key: string]: number;
            };
        };
        /** QuestionPolicyUpdate */
        QuestionPolicyUpdate: {
            question_policy: components["schemas"]["QuestionGenerationPolicy"];
        };
        /** RubricScoreItem */
        RubricScoreItem: {
            /** Criterion */
            criterion: string;
            /** Criterion Index */
            criterion_index: number;
            /** Score */
            score: number;
            /** Max Points */
            max_points: number;
            /**
             * Rationale
             * @default
             */
            rationale: string;
        };
        /** ScoringRubricItem */
        ScoringRubricItem: {
            /** Description */
            description: string;
            /** Points */
            points: number;
        };
        /** SourceReference */
        SourceReference: {
            /** Path */
            path: string;
            /**
             * Snippet
             * @default
             */
            snippet: string;
            /** Artifact Id */
            artifact_id?: string | null;
            /** Page Or Slide */
            page_or_slide?: string | null;
            /** Line Start */
            line_start?: number | null;
            /** Line End */
            line_end?: number | null;
            /** Artifact Role */
            artifact_role?: string | null;
            /** Chunk Type */
            chunk_type?: string | null;
        };
        /** StructuralFactsRead */
        StructuralFactsRead: {
            /**
             * File Count
             * @default 0
             */
            file_count: number;
            /**
             * Code File Count
             * @default 0
             */
            code_file_count: number;
            /**
             * Doc File Count
             * @default 0
             */
            doc_file_count: number;
            /**
             * Total Loc
             * @default 0
             */
            total_loc: number;
            /**
             * Test Ratio
             * @default 0
             */
            test_ratio: number;
            /** Language Loc */
            language_loc?: {
                [key: string]: unknown;
            }[];
            /** File Tree */
            file_tree?: {
                [key: string]: unknown;
            }[];
            /** Dependencies */
            dependencies?: {
                [key: string]: unknown;
            }[];
            /** Entry Point Candidates */
            entry_point_candidates?: string[];
            /** Readme Outline */
            readme_outline?: {
                [key: string]: unknown;
            }[];
        };
        /** StudentImplementationRiskRead */
        StudentImplementationRiskRead: {
            /** Area */
            area: string;
            /** Challenge */
            challenge: string;
            /** Why Difficult */
            why_difficult: string;
            /**
             * Evidence Path
             * @default
             */
            evidence_path: string;
        };
        /** StudentInterviewStateRead */
        StudentInterviewStateRead: {
            /** Session Id */
            session_id: string;
            /** Current Question Index */
            current_question_index: number;
            /** Total Questions */
            total_questions: number;
            question?: components["schemas"]["InterviewQuestionRead"] | null;
            /** Turns */
            turns?: components["schemas"]["InterviewTurnRead"][];
            /**
             * Is Completed
             * @default false
             */
            is_completed: boolean;
        };
        /** TechStackItemRead */
        TechStackItemRead: {
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Role In Project */
            role_in_project: string;
            /**
             * Evidence Path
             * @default
             */
            evidence_path: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_evaluations_api_project_evaluations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectEvaluationSummaryRead"][];
                };
            };
        };
    };
    create_evaluation_api_project_evaluations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectEvaluationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectEvaluationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_question_policy_api_project_evaluations__evaluation_id__question_policy_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionPolicyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectEvaluationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_api_project_evaluations__evaluation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectEvaluationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_status_api_project_evaluations__evaluation_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectEvaluationStatusRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_evaluation_api_project_evaluations__evaluation_id__join_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinEvaluationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinEvaluationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_zip_artifact_api_project_evaluations__evaluation_id__artifacts_zip_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_zip_artifact_api_project_evaluations__evaluation_id__artifacts_zip_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactUploadResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_artifacts_api_project_evaluations__evaluation_id__artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectArtifactRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_context_api_project_evaluations__evaluation_id__extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractedProjectContextRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_context_api_project_evaluations__evaluation_id__context_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractedProjectContextRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_questions_api_project_evaluations__evaluation_id__questions_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewQuestionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_questions_api_project_evaluations__evaluation_id__questions_get: {
        parameters: {
            query?: never;
            header?: {
                "x-session-id"?: string | null;
                "x-session-token"?: string | null;
            };
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewQuestionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_project_evaluations__evaluation_id__sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewSessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_turns_api_project_evaluations__evaluation_id__sessions__session_id__turns_get: {
        parameters: {
            query?: never;
            header?: {
                "x-session-token"?: string | null;
            };
            path: {
                evaluation_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewTurnRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_turn_api_project_evaluations__evaluation_id__sessions__session_id__turns_post: {
        parameters: {
            query?: never;
            header?: {
                "x-session-token"?: string | null;
            };
            path: {
                evaluation_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterviewTurnCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewTurnRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_interview_state_api_project_evaluations__evaluation_id__sessions__session_id__interview_state_get: {
        parameters: {
            query?: never;
            header?: {
                "x-session-token"?: string | null;
            };
            path: {
                evaluation_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentInterviewStateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transcribe_interview_audio_api_project_evaluations__evaluation_id__sessions__session_id__interview_transcribe_post: {
        parameters: {
            query?: never;
            header?: {
                "x-session-token"?: string | null;
            };
            path: {
                evaluation_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_transcribe_interview_audio_api_project_evaluations__evaluation_id__sessions__session_id__interview_transcribe_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewTranscriptionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_interview_answer_api_project_evaluations__evaluation_id__sessions__session_id__interview_answer_post: {
        parameters: {
            query?: never;
            header?: {
                "x-session-token"?: string | null;
            };
            path: {
                evaluation_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterviewTurnFlowRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewTurnFlowResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_interview_api_project_evaluations__evaluation_id__sessions__session_id__interview_complete_post: {
        parameters: {
            query?: never;
            header?: {
                "x-session-token"?: string | null;
            };
            path: {
                evaluation_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationReportRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    abort_interview_api_project_evaluations__evaluation_id__sessions__session_id__interview_abort_post: {
        parameters: {
            query?: never;
            header?: {
                "x-session-token"?: string | null;
            };
            path: {
                evaluation_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationReportRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    synthesize_interview_speech_api_project_evaluations__evaluation_id__sessions__session_id__interview_tts_post: {
        parameters: {
            query?: never;
            header?: {
                "x-session-token"?: string | null;
            };
            path: {
                evaluation_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterviewSpeechSynthesisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "audio/mpeg": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_session_api_project_evaluations__evaluation_id__sessions__session_id__complete_post: {
        parameters: {
            query?: never;
            header?: {
                "x-session-token"?: string | null;
            };
            path: {
                evaluation_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationReportRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_report_api_project_evaluations__evaluation_id__reports_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationReportRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_api_project_evaluations__evaluation_id__reports__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationReportRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_interview_page_interview__evaluation_id___session_id__open_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_interview_cookie_interview__evaluation_id___session_id__open_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_set_interview_cookie_interview__evaluation_id___session_id__open_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enter_interview_interview__evaluation_id___session_id__enter_get: {
        parameters: {
            query: {
                session_token: string;
            };
            header?: never;
            path: {
                evaluation_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_staged_interview_page_interview__evaluation_id___session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_voice_interview_page_interview__evaluation_id___session_id__voice_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    redirect_to_streamlit_report_interview__evaluation_id___session_id__report_redirect_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
